name: blog_15min

services:
  rails_app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile

    tty: true
    stdin_open: true

    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle

    ports:
      - "3000:3000"

    volumes:
      - ../:/app
      - ../blog_15min/tmp/bundle:/usr/local/bundle
      - ../blog_15min/tmp/node_modules:/app/blog_15min/node_modules

    working_dir: /app/blog_15min
    command: sleep infinity
